### PR TITLE
[1.x] Allow retrieving all features for a scope when some features are defined for differing scopes

### LINKED ISSUE #112: Using multiple scopes across features disables use of `all()` and `values()`
My project requires scoping features across multiple different models. Quick example:

```
Feature::define('beta-design', function(Team $team)...)
Feature::define('password', function(User $user)...)
```

When I configure this a Service provider, all calls to `all()` or `values()` functions throw 500 errors with incorrect parameter types. A call to `Feature::for($user)->all()` also throws errors.

I think my ideal in this situation would be instead to return a list of all features under the current model type scope, rather than throwing an error and checking them. The other alternative would be to return false for all features that are not under the scope of the model being tested. So either Feature::all() would not return any value for `beta-design` in this case, or it would return `false`. 

I am happy to code this up and add a Reflection into PendingScopedFeatureInteraction (or drivers, if that makes more sense) but wanted to confirm which expected behavior seems better. Either way, I don't like working with a system where both of these functions are completely disabled.

### PR DESCRIPTION
**Pull request by cosmastech**
This should resolve https://github.com/laravel/pennant/issues/112

We are building a feature flags endpoint for our mobile and web consumers. We need to be able to get all features for 3-4 scopes which are related to the user, but not the user object itself.

I ran into this exact issue earlier today.  I saw that this issue had been open for a few weeks without a PR so I figured I'd take a stab at it.

---

**Given** we have features defined for different scopes
```php
Feature::define('feature-for-user', fn(User $u) => true);
Feature::define('feature-for-team', fn(Team $t) => true);
```

**When** we attempt to load all features for a particular scope
```php
$features = Feature::for($user)->all()
```

**Then** we expect to receive feature flag definitions ONLY for that apply to Users.
```php
dd($features);
/*
array:1 [
  "feature-for-user" => true
]
*/
```
Currently, however, an exception is thrown: **TypeError: Tests\Feature\DatabaseDriverTest::Tests\Feature\{closure}(): Argument #1 ($t) must be of type Workbench\App\Models\Team, Workbench\App\Models\User given, called in /Users/luke/Projects/laravel-pennant/src/Drivers/Decorator.php on line 173**

## Non-goals of this PR
One outstanding question is: do we expect to allow for union or intersection types in the resolving function? Like `Feature::define('team-or-user-feature', fn(Team|User $v) => true);` Seems like this probably wouldn't work with how scopes are set up in general. I am sure that my change will *not* work in this case.

Also, you can still call `Feature::for($user)->activate('team-scoped-feature');` I believe that ideally there would be a guard for this, but it seems like it's beyond the scope of this PR.

### CODE REVIEW

File: src/PendingScopedFeatureInteraction.php [hunk 1]
```diff
@@ -146,7 +165,7 @@ public function allAreActive($features)
 
         return Collection::make($features)
             ->crossJoin($this->scope())
-            ->every(fn ($bits) => $this->driver->get(...$bits) !== false);
+            ->every(fn ($bits) => ($result = $this->driver->get(...$bits)) !== false && ! $result instanceof FeatureDoesNotMatchScope);
```
Comment (cosmastech) [inline src/PendingScopedFeatureInteraction.php]: This shouldn't be here, unless we add it to all of the methods. Going to put this back into draft to see if I can figure out how to make this work via `Driver@get()` instead

edit: actually, I think this is the right place for it: every public method has to account for the new possibility that FeatureDoesNotMatchScope is the flag result

**Comment by taylorotwell** [comment]
Drafting pending review from @timacdonald

**Comment by timacdonald** [comment]
@cosmastech, I have re-worked this one. There were a few problems with the original implementation. The main issue was when a value was resolved for a bad type, it was saved to the database.

The new implementation does the check before attempting to resolve. Supports union and intersection types.

What do you think?

`Feature::for($scope)->all()` and `Feature::for($scope)->loadAll()` will now only return or load the features for that scope type.

**Comment by cosmastech** [comment]
> @cosmastech, I have re-worked this one. There were a few problems with the original implementation. The main issue was when a value was resolved for a bad type, it was saved to the database.
> 
> The new implementation does the check before attempting to resolve. Supports union and intersection types.
> 
> What do you think?
> 
> `Feature::for($scope)->all()` and `Feature::for($scope)->loadAll()` will now only return or load the features for that scope type.

Thanks for working on this @timacdonald. Sad you removed my given-when-then 😆 but otherwise, nice.

I didn't run any local testing on this, but it seems to solve the problem. Good catch on the DB queries, didn't consider that fact.

**Review by timacdonald — APPROVED** [review]

File: src/Drivers/Decorator.php [hunk 2]
```diff
@@ -520,6 +610,28 @@ public function instance($name)
...
+     *
+     * @internal
+     *
+     * @param  mixed  $scope
+     * @return \Illuminate\Support\Collection<int, string>
+     */
+    public function definedFeaturesForScope($scope)
+    {
+        return collect($this->nameMap)
+            ->only($this->defined())
```
Comment (tomirons) [inline src/Drivers/Decorator.php:624]: @timacdonald Unfortunately this doesn't work with 3rd party services like LaunchDarkly where the features are defined in their platform.

Any thoughts on adding a check before this to see the `namedMap` is empty and if it is we load all of the features from `$this->defined()`?

An alternative could be that I retrieve all of the features from LaunchDarkly within a service provider and define them. But this just seems wrong as I can do the same thing within the `defined` method on the driver.

Comment (timacdonald) [reply src/Drivers/Decorator.php:624]: What are your thoughts on having a contract the drivers can implement to provide a list of features for the given scope?

Screenshot 2024-11-11 at 11 17 37

I suppose the thing we are trying to solve in this PR also impacts 3rd party drivers as well, so feels like we need a way for them to handle things themselves.

Comment (tomirons) [reply src/Drivers/Decorator.php:624]: This approach would be perfect!

Comment (timacdonald) [reply src/Drivers/Decorator.php:624]: Opened a PR: https://github.com/laravel/pennant/pull/127

**Comment by erikaraujo** [comment]
Hey all,

I'm still trying to figure out the exact reason (since I've never looked into this codebase before), but this PR definitely has breaking changes that should be noted in the release notes (ideally should've been release in a version 2, I think).

Again, I didn't dig too deep into the issue yet, but after this change was merged when I do `\Laravel\Pennant\Feature::all()` I get no results back.

I was using `null` scopes for a "global" FeatureFlag that is not tied to any users.

**Comment by timacdonald** [comment]
@erikaraujo, if you could open an issue with reproduction steps, I would be happy to look at the issue for you and see if we can get it resolved.

**Comment by erikaraujo** [comment]
> @erikaraujo, if you could open an issue with reproduction steps, I would be happy to look at the issue for you and see if we can get it resolved.

Hey! Thanks for the reply.
I'll open an Issue later with more details, but basically up to version 1.12 if you had any Feature Flags created you could list them by doing `Feature::all()`.

Now, that same call returns just an empty array.

**Comment by erikaraujo** [comment]
> @erikaraujo, if you could open an issue with reproduction steps, I would be happy to look at the issue for you and see if we can get it resolved.

Hey @timacdonald ! Thanks for the reply.
I'll open an Issue later with more details, but basically up to version 1.12 if you had any Feature Flags created you could list them by doing `Feature::all()`.

Now, that same call returns just an empty array.

**Comment by timacdonald** [comment]
The `Feature::all()` method should continue to return the available features for the current scope.

Would appreciate some replication steps to see the issue you are currently facing to understand it better.
