### PR TITLE
[1.x] Improve unique constraint handling for high traffic applications

### LINKED ISSUE #101: Database driver could support high frequency requests
Database driver does not work at scale, we have thousand of `SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "features_name_scope_unique"` because of the driver architecture when you have thousand requests per seconds.

As advised by @timacdonald in https://github.com/laravel/pennant/pull/77, we could use an `upsert` instead of an `insert`.

Perhaps an`insert` in a `try catch (UniqueConstraintViolationException)` should do the job because it is not really important to `update` the record several times in a single request...

### PR DESCRIPTION
**Pull request by timacdonald**
fixes #101

## Problem

Laravel Pennant implements a unique constraint that can cause race conditions:

https://github.com/laravel/pennant/blob/83178d76f41d45276da9ce37cf7d76c9f5b28945/database/migrations/2022_11_01_000001_create_features_table.php#L23

The race condition can be illustrated with the following application setup:

```sh
echo "Create project:"
composer create-project laravel/laravel pennant-race-condition
cd pennant-race-condition
composer require laravel/pennant
php artisan vendor:publish --tag=pennant-migrations
sed -i "s/DB_CONNECTION=sqlite/DB_CONNECTION=mysql/" .env
sed -i "s/# DB_DATABASE=laravel/DB_DATABASE=pennant_race_condition/" .env
php artisan migrate --force

echo "Create command to invoke:"
echo "<?php

use Illuminate\Foundation\Inspiring;
use Illuminate\Support\Facades\Artisan;
use Laravel\Pennant\Feature;

Artisan::command('dev', function () {
    \$name = 'foo-'.time();

    Feature::define(\$name, fn () => 'okay');

    echo Feature::value('foo-'.time()).PHP_EOL;
});" > routes/console.php

echo "Create script that will invoke the command simulating high traffic:"
echo "php artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nwait\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nwait\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nwait\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nwait\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nwait\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nwait\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nwait\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nwait\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nwait\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nphp artisan dev &\nwait" > script.sh
```

To simulate the race condition, you may invoke the script:

```sh
bash script.sh
```

## Solution

We now retry when hitting a `UniqueConstraintViolationException`. For a single feature , we only retry once, i.e., two total attempts. For several individual features, via `getAll`, we retry twice, i.e., 3 total attempts.

This is similar to how the framework handles these internally with `createOrFirst`.

## Why not a cache lock

For indivdual features, we could use a cache lock.

When retrieving several features at a time, like you might do with `Feature::loadMissing([/* ... */]);` to avoid n+1 queries, a cache lock becomes complicated.

We would need an indivudal cache lock for each feature you are loading. We would need to aquire the cache lock before retrieving, which means every single feature retrievial now requires a cache lock, even if it will never result in a race condition.

If you are using the database driver, now you have increased the queries required to retrieve a feature.

I feel that simply retrying for those rare cases where a race condition will occur is the best way forward. It means 99% of retrievals happen with not speed impact and there is a small cost when a race condition happens to occur.

### CODE REVIEW

File: src/Drivers/DatabaseDriver.php [hunk 1]
```diff
@@ -276,24 +313,13 @@ public function setForAllScopes($feature, $value): void
...
+        return (bool) $this->newQuery()
             ->where('name', $feature)
-            ->where('scope', $serialized)
+            ->where('scope', Feature::serializeScope($scope))
             ->update([
                 'value' => json_encode($value, flags: JSON_THROW_ON_ERROR),
                 static::UPDATED_AT => Carbon::now(),
             ]);
-
-        return true;
```
Comment (timacdonald) [inline src/Drivers/DatabaseDriver.php:296]: This was needlessly doing two queries: 1 to check the existence and another to make the update.

Updated to only do a single update statement to better support high traffic applications and reduce queries.

File: src/Drivers/DatabaseDriver.php [hunk 2]
```diff
@@ -245,9 +278,13 @@ protected function resolveValue($feature, $scope)
...
-        if (! $this->update($feature, $scope, $value)) {
-            $this->insert($feature, $scope, $value);
-        }
+        $this->newQuery()->upsert([
+            'name' => $feature,
+            'scope' => Feature::serializeScope($scope),
+            'value' => json_encode($value, flags: JSON_THROW_ON_ERROR),
+            static::CREATED_AT => $now = Carbon::now(),
+            static::UPDATED_AT => $now,
+        ], uniqueBy: ['name', 'scope'], update: ['value', 'updated_at']);
```
Comment (timacdonald) [inline src/Drivers/DatabaseDriver.php:287]: When telling Pennant to set a feature, we now utilise `upsert` instead of attempting to update and then insert if there is nothing to update. This has a positive impact on the number of database queries the library runs.

**Comment by StSarc** [comment]
@timacdonald This might be the wrong place to ask, but since it's related, asking here (please let me know if you prefer me creating a issue instead, I'll do that right away)

Can we have `insertAll` function similar to the [`insert` function present in the databaseDriver already](https://github.com/timacdonald/pennant/blob/1.x/src/Drivers/DatabaseDriver.php#L307-L316) instead of having the [query explicit in the getAll function for inserting all](https://github.com/laravel/pennant/pull/104/files#diff-1a43ceac96375e5f6481c0664cd948657ac011cb3c0ee0be9959bee4bafaf9d2R183)?

If it makes sense, I can raise a PR for the same.

This will primarily help with overriding functions in DatabaseDriver. Currently, I just need to override the "writes" to the DB. But, since we have a write inside the `getAll` function, I have to override the `getAll` function too unnecessarily.
Related issue by someone else: https://github.com/laravel/pennant/issues/100

**Comment by timacdonald** [comment]
I don't see anything wrong with an `insertMany` extracted function 👍

**Comment by timacdonald** [comment]
https://github.com/laravel/pennant/pull/105
